name: Oppose Gravity
favicon: null
layout_spectrum: 0.70791
typography_spectrum: 0.32282
title: Oppose Gravity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73496378-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2e2e2e'
    - '#959595'
    - '#575757'
  brandStrength: 0.6875
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
