name: Oppose Gravity
favicon: null
layout_spectrum: 0.00495
typography_spectrum: 0.45173
title: Oppose Gravity
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f0eada'
    - '#1f2b39'
    - '#e93a0d'
    - '#484848'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
