name: Oppose Gravity
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1a17'
    - '#ffffff'
    - '#423d3b'
    - '#a9a7a6'
    - '#6a6765'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
