typography_spectrum: 0.32282
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#2e2e2e'
    - '#959595'
    - '#575757'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.70791
analytics:
  google: UA-73496378-1
  facebook: null
  twitter: null
name: Oppose Gravity
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Oppose Gravity
purpose: []
